title: ViSparJek
description: vivo explorer + jekyll 
show_downloads: true
google_analytics:


collections:
  facultymembers:
    output: true
    permalink: /:path/

defaults:
  - scope:
      type: facultymembers
    values:
      layout: default